spec:
  inputs:
    cloud-provider:
      type: string
      default: 'aws'
      description: "Cloud provider for VPN"
      options: ['aws', 'gcp', 'do']
    region:
      description: "Regional deployment target"
      rules:
        - if: $[[ inputs.cloud-provider ]] == 'aws'
          default: 'ap-southeast-1'
          options: [
            'us-east-1', 'us-east-2', 'us-west-1', 'us-west-2', 'af-south-1', 'ap-east-1', 'ap-east-2', 
            'ap-south-1', 'ap-south-2', 'ap-northeast-1', 'ap-northeast-2', 'ap-northeast-3', 'ap-southeast-1', 
            'ap-southeast-2', 'ap-southeast-3', 'ap-southeast-4', 'ap-southeast-5', 'ap-southeast-6', 
            'ap-southeast-7', 'ca-central-1', 'ca-west-1', 'eu-central-1', 'eu-central-2', 'eu-west-1', 
            'eu-west-2', 'eu-west-3', 'eu-south-1', 'eu-south-2', 'eu-north-1', 'il-central-1', 'me-south-1', 
            'me-south-2', 'me-central-1', 'mx-central-1', 'sa-east-1', 'us-gov-east-1', 'us-gov-west-1', 
            'cn-north-1', 'cn-northwest-1'
          ]
        - if: $[[ inputs.cloud-provider ]] == 'gcp'
          default: 'asia-southeast1'
          options: [
            'africa-south1', 'asia-east1', 'asia-east2', 'asia-northeast1', 'asia-northeast2', 'asia-northeast3', 
            'asia-south1', 'asia-south2', 'asia-southeast1', 'asia-southeast2', 'australia-southeast1', 
            'australia-southeast2', 'europe-central2', 'europe-north1', 'europe-north2', 'europe-southwest1', 
            'europe-west1', 'europe-west2', 'europe-west3', 'europe-west4', 'europe-west6', 'europe-west8', 
            'europe-west9', 'europe-west10', 'europe-west12', 'me-central1', 'me-central2', 'me-west1', 
            'northamerica-northeast1', 'northamerica-northeast2', 'northamerica-south1', 'southamerica-east1', 
            'southamerica-west1', 'us-central1', 'us-east1', 'us-east4', 'us-east5', 'us-south1', 'us-west1', 
            'us-west2', 'us-west3', 'us-west4'
          ]
        - if: $[[ inputs.cloud-provider ]] == 'do'
          default: 'sgp1'
          options: ['nyc1', 'nyc2', 'nyc3', 'ams3', 'sfo2', 'sfo3', 'sgp1', 'lon1', 'fra1', 'tor1', 'blr1', 'syd1', 'atl1']
    instance-type:
      description: "VPN server instance type"
      rules:
        - if: $[[ inputs.cloud-provider ]] == 'aws'
          default: 't2.micro'
          options: ['t2.micro', 't3.micro', 't2.small', 't3.small', 't2.medium', 't3.medium']
        - if: $[[ inputs.cloud-provider ]] == 'gcp'
          default: 'e2-micro'
          options: ['e2-micro', 'e2-small', 'e2-medium']
        - if: $[[ inputs.cloud-provider ]] == 'do'
          default: 's-1vcpu-1gb'
          options: ['s-1vcpu-1gb', 's-1vcpu-512mb-10gb', 's-1vcpu-2gb']
---
stages:
  - provision
  - prepare
  - install
  - generate
  - destroy

variables:
  AWS_SSH_USER: "ubuntu"
  GCP_SSH_USER: "vpnadmin"
  DO_SSH_USER: "root"
  PROVIDER: $[[ inputs.cloud-provider ]]
  REGION: $[[ inputs.region ]]
  INSTANCE_TYPE: $[[ inputs.instance-type ]]
  ENVIRONMENT_NAME: $[[ inputs.cloud-provider ]]-$[[ inputs.region ]]-${CI_PIPELINE_IID}

include:
  - local: 'pipeline/providers/aws.yaml'
    rules:
      - if $[[ inputs.cloud-provider ]] == 'aws'
  - local: 'pipeline/providers/gcp.yaml'
    rules:
      - if $[[ inputs.cloud-provider ]] == 'gcp'
  - local: 'pipeline/providers/do.yaml'
    rules:
      - if $[[ inputs.cloud-provider ]] == 'do'
  - local: 'pipeline/templates/*.yaml'
